export const SET_ALL_TOURNAMENTS = 'SET_ALL_TOURNAMENTS';
export const THROW_ERROR_ON_LOADING = 'THROW_ERROR_ON_LOADING';
export const EDIT_TOURNAMENT = 'EDIT_TOURNAMENT';
export const START_LOADING = 'START_LOADING';
